apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: prod
  labels:
    name: postgres-db
    type: back-end
    app: quarkus-user-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres-db
        type: back-end
        app: quarkus-user-service
    spec:
      containers:
        - name: postgres-container
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-db
          volumeMounts:
            - mountPath: /var/lib/postgres-db-env-prod/data
              name: postgres-db
      volumes:
        - name: postgres-db
          persistentVolumeClaim:
            claimName: postgres-db
  selector:
    matchLabels:
      name: postgres-db
      type: back-end
      app: quarkus-user-service
