apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db
  namespace: test
  labels:
    name: postgres-db
    type: back-end
    app: quarkus-user-service
data:
  POSTGRES_DB: quarkus-user-service-db
  POSTGRES_USER: developer
  POSTGRES_PASSWORD: strong_password
