apiVersion: v1
kind: Service
metadata:
  name: some-service
  labels:
    app: some-app
    type: some-type
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 8080
  selector:
    app: some-app-label
    type: some-type-label
