apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: back-end
spec:
  containers:
    - name: nginx-container
      image: nginxf
      ports:
        - containerPort: 8080
  volumes:
    - name: app-secret-volume
      configMap:
        name: name-of-secret-file
