apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness-http
spec:
  containers:
    - name: readiness
      image: k8s.gcr.io/liveness
      args:
        - /server
      ports:
        - name: readiness-port
          containerPort: 8080
          hostPort: 8080
      livenessProbe:
        httpGet:
          path: /is_ready
          port: readiness-port
          httpHeaders:
            - name: Custom-Header
              value: Awesome
        initialDelaySeconds: 3
        periodSeconds: 3
