apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistentVolumeClaim
  namespace: namespace
  labels:
    name: label-name
    type: label-type
    app: label-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
